### ISSUE TITLE
Not raising "errno.ENOENT"

### ISSUE THREAD

**Issue by GuidoBR** [mitsuhiko/python-inifile#4]
I have noticed that you decided to not raise "No such file or directory" errors, instead you choose to create a new INI config file when a file that doesn't exists is used with this library.

That's causing problems with lektor plugins. If I make a typo (for example using "config" instead of "configs" directory, it's not clear from the error message I get what was really the cause.

"raise RuntimeError('Disqus shortname not configured')"

Maybe it could have some parameter to decide what happens when a file can't be found. It would be useful for that project, and easy to implement.

Thanks for your time!

**Comment by mitsuhiko** [comment]
Not sure why that would require raising an error.  There already is a flag that indicates if the file is absent.  This is more of a thing in lektor plugins that their error message should probably indicate absent files.  It's perfectly legitimate in lektor for config files to not exist for plugins.
